project:
  type: website

website:
  title: "Talks"
  navbar:
    left:
      - href: glm/glm.qmd
        text: GLM
      - href: ttest/ttest.qmd
        text: t-test
      - href: intro_r_cognition/workshop_guide.qmd
        text: intro-r-cognition

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

execute:
  freeze: auto
