---
title: "Simuldate data for workshop"
format: 
    html:
        df-print: kable
---

## Setup

```{r}
library(faux)
library(tidyverse)
library(ggplot2)
library(here)
set.seed(34)
```

## Simulate data
### DSF

```{r}
between <- list(group = c("healthy", "depression"))
means <- list(
    c("healthy" = 6, "depression" = 5)
)
sds <- list(
    c("healthy" = 2, "depression" = 2)
)

data_dsf <- sim_design(
    between = between,
    mu = means,
    sd = sds,
    n = 50,
    dv = "digit_span_forward"
)
head(data_dsf)
str(data_dsf)
```

### DSB

```{r}
between <- list(group = c("healthy", "depression"))
means <- list(
    c("healthy" = 5.5, "depression" = 4.5)
)
sds <- list(
    c("healthy" = 1.5, "depression" = 1.5)
)

data_dsb <- sim_design(
    between = between,
    mu = means,
    sd = sds,
    n = 50,
    dv = "digit_span_backward"
)
head(data_dsb)
str(data_dsb)
```

### Merge data

```{r}
data <- merge(
    data_dsf, 
    data_dsb[, c("id", "digit_span_backward")],
    by = "id"
)
head(data)
dim(data)
```

## Format data

```{r}
data <- data |>
    mutate(
        across(
            where(is.numeric),
            round,
            0
        )
    )
head(data)
```

## Fix impossible values

```{r}
data <- data |>
    mutate(
        digit_span_forward = if_else(
            digit_span_forward < 2,
            2,
            digit_span_forward
        ),
        digit_span_backward = if_else(
            digit_span_backward < 2,
            2,
            digit_span_backward
        ),
    )
```

## Check data

```{r}
data |>
    group_by(group) |>
    summarise(
        min_dsf = min(digit_span_forward),
        mean_dsf = mean(digit_span_forward),
        sd_dsf = sd(digit_span_forward),
        max_dsf = max(digit_span_forward),
        min_dsb = min(digit_span_backward),
        mean_dsb = mean(digit_span_backward),
        sd_dsb = sd(digit_span_backward),
        max_dsb = max(digit_span_backward)
    )
```

## Save data


```{r}
path_data <- here('intro_r_cognition/data.csv')
data |>
    write_csv(path_data)
```