---
title: "Script that will be developed during the workshop"
format: 
    html:
        df-print: kable
---

## Setup

```{r}
library(tidyverse)
```

## Read data

```{r}
data <- read_csv("https://raw.githubusercontent.com/mario-bermonti/talks/refs/heads/main/intro_r_cognition/data.csv")
```

## Inspect the data

```{r}
head(data)
```

```{r}
dim(data)
```

```{r}
str(data)
```

## Effect of MDD on digit span forward

### Viz

#### Box plot

##### Basic 
```{r}
boxplot(digit_span_forward ~ group, data)
```

##### Advanced (more powerful)
```{r}
ggplot(
    data,
    aes(x = group, y = digit_span_forward)
) +
geom_boxplot()
```

#### Bar plot


Let's calculate the means we will plot

```{r}
means <- data |>
    group_by(group) |>
    summarise(
        mean_dsf = mean(digit_span_forward),
        mean_dsb = mean(digit_span_backward)
    )

means
```

##### Basic

```{r}
barplot(mean_dsf ~ group, data = means)
```

##### Advanced (more powerful)

```{r}
ggplot(
    data = means,
    aes(x = group, y = mean_dsf)
) + 
geom_bar(stat = "identity")
```

#### Violin plot

```{r}
library(see)
ggplot(
    data,
    aes(x = group, y = digit_span_forward)
) + 
geom_violindot()
```

### Descriptive stats

#### General

```{r}
data |>
    summarise(
        mean_dsf = mean(digit_span_forward),
        sd_dsf = sd(digit_span_forward),
        min_dsf = min(digit_span_forward),
        max_dsf = max(digit_span_forward)
    )
```

#### By group

```{r}
data |>
    group_by(group) |>
    summarise(
        mean_dsf = mean(digit_span_forward),
        sd_dsf = sd(digit_span_forward),
        min_dsf = min(digit_span_forward),
        max_dsf = max(digit_span_forward)
    )
```

### Inferential
